version: "3.9"

services:
  node-server:
    container_name: node-server
    image: node_mongo_custom
    volumes:
      - "/root/projects/mern-app/BE-nodeExpress:/usr/src"
    environment:
      - NODE_ENV=development
    env_file:
      - mongoDB-credential.env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  mongoDB:
    container_name: "mongoDB"
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_mern_data:/data/db
      - mongo_test_config:/data/configdb
    env_file:
      - mongoDB-credential.env
volumes:
    mongo_mern_data:
      external: true
    mongo_mern_config:
      external: true
