version: "3.9"

services:
  node-server:
    image: node_mongo_custom
    ports:
      - 4000:4000
    volumes:
      - "/root/projects/mern-app/BE-nodeExpress:/usr/src"
      - "/root/project-imgs:/usr/imgs"
      - "/etc/letsencrypt:/etc/letsencrypt"
    environment:
      - NODE_ENV=production
    env_file:
      - mongoDB-credential.env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  website:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/root/projects/mern-app/FE-react/build:/etc/nginx/html"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/root/projects/mern-app/BE-docker/nginx.conf:/etc/nginx/nginx.conf"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  mongodb1:
    container_name: "mongodb"
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data-prod:/data/db
      - mongo-cfg-prod:/data/configdb
    expose:
      - "27017"
    env_file:
      - mongoDB-credential.env
  gl-server:
    container_name: "gl-server"
    image: maptiler/tileserver-gl:latest
    ports:
      - 8080:80
    volumes:
      - /root/openmaptiles/data:/data

volumes:
    mongo-data-prod:
      external: true
    mongo-cfg-prod:
      external: true
