version: "3.9"

services:
  node-server:
    container_name: node-server
    image: node_mongo_custom
    ports:
      - 4000:4000
    volumes:
      - "/root/projects/mern-app/BE-nodeExpress:/usr/src"
    environment:
      - NODE_ENV=development
    env_file:
      - mongoDB-credential.env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  mongodb1:
    container_name: "mongodb1"
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data_1:/data/db
      - mongo_config_1:/data/configdb
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    env_file:
      - mongoDB-credential.env
  mongodb2:
    container_name: "mongodb2"
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data_2:/data/db
      - mongo_config_2:/data/configdb
    env_file:
      - mongoDB-credential.env
    expose:
      -  "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
  mongodb3:
    container_name: "mongodb3"
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data_3:/data/db
      - mongo_config_3:/data/configdb
    env_file:
      - mongoDB-credential.env
    expose:
      -  "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]
  gl-server:
    container_name: "gl-server"
    image: maptiler/tileserver-gl:latest
    ports:
      - 8080:80
    volumes:
      - /root/openmaptiles/data:/data

volumes:
    mongo_data_1:
      external: true
    mongo_config_1:
      external: true
    mongo_data_2:
      external: true
    mongo_config_2:
      external: true
    mongo_data_3:
      external: true
    mongo_config_3:
      external: true
