version: "3.9"

services:
  webservice:
    container_name: webservice
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "/root/projects/mern-app/FE-react/build:/etc/nginx/html"
      - "/root/projects/mern-app/BE-nginx/nginx.conf:/etc/nginx/nginx.conf"