version: "3.9"

services:
  webservice:
    container_name: webservice
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/root/projects/mern-app/FE-react/build:/etc/nginx/html"
      - "/root/projects/mern-app/BE-nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
  map_server:
    container_name: map_server
    image: maptiler/tileserver-gl:latest
    expose:
      - 80
    depends_on:
      - webservice
    volumes:
      - /root/tileserver-gl/data:/data  
  backend:
    container_name: backend
    image: node_mongo_custom
    ports:
      - 4000:4000
    volumes:
      - "/root/projects/mern-app/BE-nodeExpress:/usr/src"
    environment:
      - NODE_ENV=production
    env_file:
      - mongoDB-credential.env
    stdin_open: true
    tty: true
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongo-data-prod:/data/db
      - mongo-cfg-prod:/data/configdb
    expose:
      - 27017
    env_file:
      - mongoDB-credential.env

volumes:
  mongo-data-prod:
    external: true
  mongo-cfg-prod:
    external: true
